
[[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//linkedin.com/in/james-bovell"

 [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/jamesbovell"
